apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-traefik
  namespace: argocd
spec:
  project: default
  source:
  repoURL: "https://github.com/asmglobal-cloud/asmglobal-gitops.git"
  targetRevision: main
  path: infra/traefik/base
  helm:
    releaseName: traefik
    chart: traefik
    repoURL: https://traefik.github.io/charts
    version: 23.1.0
    values: |
      serviceAccount:
        create: true
      additionalArguments:
        - "--api.dashboard=true"

