apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ../../base
  - middleware-dashboard-auth.yaml
  - dashboard-ingressroute.yaml
  - hostinger-secret.yaml

helmCharts:
  - name: traefik
    releaseName: traefik
    namespace: traefik
    repo: https://traefik.github.io/charts
    version: 23.1.0
    valuesFile: ../../base/values.yaml
