apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ../../base
  - middleware-dashboard-auth.yaml
  - dashboard-ingressroute.yaml
  - dashboard-auth-secret.yaml
  - hostinger-secret.yaml
