apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - middleware-dashboard-auth.yaml
  - dashboard-ingressroute.yaml
  - dashboard-auth-secret.yaml
  - hostinger-secret.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 23.1.0
    releaseName: traefik
    valuesFile: values-base.yaml

  - name: traefik
    repo: https://traefik.github.io/charts
    version: 23.1.0
    releaseName: traefik
    valuesFile: values-production.yaml
