apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 61.2.0
    releaseName: prometheus
    valuesFile: values.yaml

  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: 2.10.2
    releaseName: loki
    valuesInline:
      grafana:
        enabled: false   # disable duplicate Grafana (prometheus stack provides Grafana)
