apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - repo-server-network.yaml
  - repo-server-egress.yaml

patchesStrategicMerge:
  - repo-server-network.yaml

