apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# list resources you *want to apply* (e.g. networkpolicy file)
resources:
  - repo-server-egress.yaml

# only reference the patch here â€” do NOT list repo-server-network.yaml under resources
patchesStrategicMerge:
  - repo-server-network.yaml
