apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base
  - repo-server-egress.yaml
  - redis-allow-networkpolicy.yaml

patches:
  - path: repo-server-capabilities-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-repo-server
